from __future__ import annotations

import re
import string


IDENT_START = string.ascii_letters + "_"
IDENT_BODY = string.ascii_letters + string.digits + "_"

RESERVED = {
    "and",
    "break",
    "do",
    "else",
    "elseif",
    "end",
    "false",
    "for",
    "function",
    "goto",
    "if",
    "in",
    "local",
    "nil",
    "not",
    "or",
    "repeat",
    "return",
    "then",
    "true",
    "until",
    "while",
    "continue",
    "export",
    "type",
    "typeof",
}

PROTECTED_NAMES = RESERVED | {
    "_G",
    "_ENV",
    "game",
    "script",
    "workspace",
    "shared",
    "getgenv",
    "setgenv",
    "getfenv",
    "setfenv",
    "loadstring",
    "load",
    "pcall",
    "xpcall",
    "error",
    "assert",
    "warn",
    "print",
    "pairs",
    "ipairs",
    "next",
    "select",
    "type",
    "typeof",
    "tostring",
    "tonumber",
    "rawget",
    "rawset",
    "rawequal",
    "rawlen",
    "setmetatable",
    "getmetatable",
    "collectgarbage",
    "unpack",
    "string",
    "table",
    "math",
    "bit32",
    "utf8",
    "buffer",
    "task",
    "os",
    "debug",
    "coroutine",
    "Instance",
    "Enum",
    "Vector2",
    "Vector3",
    "Vector2int16",
    "Vector3int16",
    "UDim",
    "UDim2",
    "CFrame",
    "Color3",
    "BrickColor",
    "RaycastParams",
    "OverlapParams",
    "TweenInfo",
    "NumberRange",
    "NumberSequence",
    "ColorSequence",
    "Rect",
    "Random",
    "DateTime",
    "PhysicalProperties",
    "Region3",
    "Region3int16",
    "Ray",
    "tick",
    "time",
    "wait",
    "spawn",
    "delay",
    "plugin",
    "NexusProtect",
    "NEXUS_ENCSTR",
    "NEXUS_ENCFUNC",
    "NEXUS_GUARD",
    "NEXUS_NO_VIRTUALIZE",
    "NEXUS_WATERMARK",
    "LPH_ENCSTR",
    "LPH_ENCFUNC",
    "LPH_NO_VIRTUALIZE",
    "LPH_JIT",
    "LPH_JIT_MAX",
}

SENSITIVE_NAME_RE = re.compile(
    r"(auth|valid|validate|license|key|hwid|nonce|signature|sign|heartbeat|request|"
    r"tamper|integrity|spoof|session)",
    re.IGNORECASE,
)

