export enum LuaSyntaxKind {
  Program = "Program",
  LocalDeclaration = "LocalDeclaration",
  AssignmentStatement = "AssignmentStatement",
  CallStatement = "CallStatement",
  ReturnStatement = "ReturnStatement",
  FunctionDeclaration = "FunctionDeclaration",
  ControlStatement = "ControlStatement",
  UnknownStatement = "UnknownStatement",
  IdentifierExpression = "IdentifierExpression",
  BinaryExpression = "BinaryExpression",
  StringLiteral = "StringLiteral",
  NumericLiteral = "NumericLiteral",
  BooleanLiteral = "BooleanLiteral",
  NilLiteral = "NilLiteral",
  VarargExpression = "VarargExpression",
  UnknownExpression = "UnknownExpression",
}

export enum ProtectionStep {
  WrapInFunction = "WrapInFunction",
  AddVararg = "AddVararg",
  ConstantArray = "ConstantArray",
  EncryptStrings = "EncryptStrings",
  SplitStrings = "SplitStrings",
  NumbersToExpressions = "NumbersToExpressions",
  ProxifyLocals = "ProxifyLocals",
  AntiTamper = "AntiTamper",
  Watermark = "Watermark",
  WatermarkCheck = "WatermarkCheck",
  Vmify = "Vmify",
  TableKeys = "TableKeys",
  Globals = "Globals",
  ControlFlow = "ControlFlow",
  OpaquePredicates = "OpaquePredicates",
}
